dist: xenial
language: node_js
node_js:
  - "6"
cache:
  yarn: true
install:
  - yarn
script:
  - yarn install
  - yarn test
  - yarn build
deploy:
  provider: pages
  local_dir: react-app/build/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: react-app-src
  target_branch: master

